version: '3'
services:
  node-app:
    image: node:latest
    container_name: node-app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "5000:5000"
    command: npm start
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    - ./nginx:/etc/nginx/conf.d
    depends_on:
      - node-app

volumes:
  mysql-data:
  mongo-data: